name: Build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: License check
        run: mvn -B license:check

      - name: Build with Maven skipTests
        run: mvn -B clean install -DskipTests

      #- name: Style check
      #  run: mvn -B checkstyle:check

      - name: Spotbugs check
        run: mvn -B spotbugs:check

      - name: pulsar-rabbitmq-gw tests
        run: mvn -B test -DfailIfNoTests=false -pl pulsar-rabbitmq-gw

      - name: RabbitMQ Java client tests
        run: mvn -B test -DfailIfNoTests=false -pl rabbitmq-tests